### ISSUE TITLE
As a game developer I want to see wire frame of physics shape in scene view so I can recognize the volume of the shape easily

### ISSUE THREAD

**Issue by ContentsViewer** [nodec-project/nodec_game_engine#19]
That is, support Gizmo.

- [x] nodec-project/nodec_scene_editor#2
- [x] nodec-project/nodec_game_engine#39
- [x] nodec-project/hello-nodec-game#7

**Comment by ContentsViewer** [comment]
DONE!

<img width="1019" alt="image" src="https://github.com/nodec-project/nodec_game_engine/assets/25942144/c79c37b6-3e20-4166-9ace-977b9fca2a82">
