### ISSUE TITLE
As a game developer I want to load animation file so I can animate the entity without coding

### ISSUE THREAD

**Issue by ContentsViewer** [nodec-project/nodec_game_engine#8]
## Tasks

- [x] nodec-project/nodec_animation#1
- [x] nodec-project/nodec_animation#3
- [x] nodec-project/nodec_animation#4
- [ ] Implement sampling properties of components from entity (nodec_animation)
